Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-7.0"

  #  config.vm.network :private_network, ip: "192.168.33.50"

  #  gitlab-certs executor for personal usage only
  #  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/gitlab-certs.sh"

  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/epel.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/dev-tools.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/php53.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/php-composer.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/php-codesniffer.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/apache.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/mysql.sh"
  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/magento-cli.sh"

end