Vagrant.configure("2") do |config|
  config.vm.box = "Berkshelf-CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/31081437/Berkshelf-CentOS-6.3-x86_64-minimal.box"
  config.vm.network :private_network, ip: "192.168.33.50"

#  gitlab-certs executor for personal usage only
#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/gitlab-certs.sh"

#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/epel.sh"
#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/dev-tools.sh"
#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/php53.sh"
#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/php-composer.sh"
#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/apache.sh"
#  config.vm.provision "shell", path: "./vendor/speroteck/magento-vagrant-integration/modules/mysql.sh"

end